// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuqzandxhmqzkhsddqrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1cXphbmR4aG1xemtoc2RkcXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MjgwNDEsImV4cCI6MjA2MDUwNDA0MX0.JGkzpyKOrG9afncWYwJ02Ym8CERTCQvl4LlRobTwM3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);